### PR TITLE
Use backticks for keywords in NameAllocator

### PR DESCRIPTION
**Pull request by Egorand**

### CODE REVIEW

**Comment by JakeWharton** [comment]
One problem with this is that if you use the name in an output somewhere it will become backticked. You can see this in your Wire PR where the `toString()` becomes `` `when`=blah `` instead of `when=blah`.

**Comment by JakeWharton** [comment]
Can we return "when" and require the use of `%N` which does(?) the backtick escaping?

**Comment by Egorand** [comment]
Yep, `%N` does backticks. Do you mean require its use in Wire? I think it's worth trying!

**Comment by JakeWharton** [comment]
> Do you mean require its use in Wire?

I more meant in general. If we start returning "when" directly, then people using string templating will start to get code that doesn't compile. Are we comfortable saying "You should have been using/must use %N"?

**Comment by Egorand** [comment]
I think eventually (in 2.0 probably?) we should do that. To avoid breaking current behaviour though, @swankjesse & I decided to introduce API to control how keywords are treated: #1803.

**Comment by Egorand** [comment]
Closed in favour of #1803.

**Pull request closed without merging**
