### PR TITLE
Add MemberName.isExtension and update importing logic

### LINKED ISSUE #1089: KotlinPoet wrongly inlines extension functions
KotlinPoet seems to be inlining extensions functions like if they were members and this generates non-compilable code.

Here's a diff of our before/after.

```diff
 import kotlin.Long
 import kotlin.String
 import kotlin.Unit
-import kotlin.hashCode
 import kotlin.jvm.JvmField
 import okio.ByteString

@@ -55,8 +54,8 @@ public class OuterMessage(
     var result = super.hashCode
     if (result == 0) {
       result = unknownFields.hashCode()
-      result = result * 37 + outer_number_before.hashCode()
-      result = result * 37 + embedded_message.hashCode()
+      result = result * 37 + outer_number_before.kotlin.hashCode()
+      result = result * 37 + embedded_message.kotlin.hashCode()
       super.hashCode = result
     }
     return result
```

It breaks Wire when we bump KotlinPoet from `1.7.2` to `1.8.0`.
I think that's a side-effect of https://github.com/square/kotlinpoet/pull/1040 ?

### PR DESCRIPTION
**Pull request by Egorand**
Fixes #1089

### CODE REVIEW

**Review by oldergod — APPROVED** [review]
I wonder if people would wrongly assume `isExtension` will be set for them

**Comment by Egorand** [comment]
@oldergod as in, thinking it's a computed property vs a constructor parameter? Any updates to the docs you can suggest that would make this more clear?

**Comment by oldergod** [comment]
Is there a way to ever get a member not manually created? If no, then it might be ok.
If yes, a comment on the field would be good.

**Comment by Egorand** [comment]
No, I don't think we're ever inferring `MemberName`s from some other type of input, we expect them to only be created externally.

**Pull request merged**
