### PR TITLE
Add .editorconfig & remove ktLint rules

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by ZacSweers** [comment]
Start an issue to discuss first and explain what the benefit is, this seems like needless change for the sake of change

**Comment by Goooler** [comment]
> Start an issue to discuss first and explain what the benefit is, this seems like needless change for the sake of change

For better edit experience in IDEA, because auto reformat by idea will change the indent size to 4

**Comment by Egorand** [comment]
@Goooler does IDEA pick up `.editorconfig` automatically? We ship [java-code-styles](https://github.com/square/java-code-styles) which would be optimal for Square open source contributors, but a bit more effort to setup, and I also don't see it mentioned in our Contributing guide.

**Comment by Goooler** [comment]
> @Goooler does IDEA pick up `.editorconfig` automatically? We ship [java-code-styles](https://github.com/square/java-code-styles) which would be optimal for Square open source contributors, but a bit more effort to setup, and I also don't see it mentioned in our Contributing guide.

Yeah, load `.editorconfig` automatically, or you should add `.idea/codeStyle/codeStyleConfig.xml` in project for more convenience.

**Comment by Egorand** [comment]
Sorry for the late reply @Goooler, I think we want this. I opened an issue (#1104), if you'd like to re-submit this PR add a "Fixes #1104" to the description.

**Pull request closed without merging**
