### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Goooler**
- [Gradle 7.1.1](https://docs.gradle.org/7.1.1/release-notes.html)
- [gradle-maven-publish-plugin 0.17.0](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/CHANGELOG.md#version-0170-2021-07-04)
- [Auto common 1.1](https://github.com/google/auto/releases/tag/auto-common-1.1)
- ~~Add [dependabot](https://dependabot.com/) for automated dependency updates~~

### CODE REVIEW

**Review by ZacSweers — COMMENTED** [review]
Does dependabot work for the way our dependencies are managed?

**Comment by Egorand** [comment]
TBH I find dependabot too noisy and I wouldn't want us to use it - I can be convinced otherwise if other maintainers strongly support it. This library only really depends on the Kotlin stdlib, which we're pretty diligent about keeping up to date anyway. Bumping all of the test dependencies on a regular basis doesn't feel very useful to me.

**Comment by ZacSweers** [comment]
I agree, it's too limited in anything but the most trivial gradle projects too

**Comment by Goooler** [comment]
> I agree, it's too limited in anything but the most trivial gradle projects too

Ok, I reverted.

**Review by Egorand — APPROVED** [review]
Thanks!

**Pull request merged**
