### PR TITLE
Fix #1104: Add .editorconfig

### LINKED ISSUE #1104: Add .editorconfig
Square's code style enforces 2-space indents, contrary to many other official and unofficial code styles. To make it easier for contributors to follow the correct code style, we can add an `.editorconfig` file to the root of the repo. IDEs such as Intellij IDEA should pick it up and apply the settings.

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #1104 

added indent size to 2

### CODE REVIEW

**Comment by anandwana001** [comment]
@Egorand PTAL

**Comment by ZacSweers** [comment]
Please don't @ mention maintainers asking for reviews. We get notifications and will look at PRs when we have time.

**Comment by JakeWharton** [comment]
I would suggest grabbing an editor config copy from turbine or something else on cashapp which are ever-so slightly more comprehensive (while still minimal).

**Review by Egorand — APPROVED** [review]
Thanks! Just one more thing - please sign our [CLA](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1)!

**Comment by anandwana001** [comment]
> CLA

Done, Thanks

**Pull request merged**
