### PR TITLE
Remove superfluous Kind definitions

### PR DESCRIPTION
**Pull request by Egorand**

### CODE REVIEW

**Comment by swankjesse** [comment]
Yah I like this.

**Comment by Egorand** [comment]
@JakeWharton @swankjesse do you think `ENUM` and `ANNOTATION` should go as well?

**Comment by swankjesse** [comment]
Unsure. I didn’t like `expect` because it seemed like that might stack with other modifiers like `external`.

For `enum` and `annotation`, it mostly comes down to whatever is easier to understand and maintain.

**Comment by JakeWharton** [comment]
I think so, since that's how the language models it.

**Comment by Egorand** [comment]
Have been playing around with it, removing `ENUM` and `ANNOTATION` adds a ton of clutter: every time we `require(kind == ANNOTATION)` we'll now have to `require(kind == CLASS && ANNOTATION !in modifers)` and so on. While `EXPECT` and `EXTERNAL` can attach to any type, `ENUM` and `ANNOTATION` only make sense with a `class`, hence it's probably fine to model them as separate kinds. Maybe there's a cleaner solution that I'm missing.

**Comment by JakeWharton** [comment]
That seems like something that can be hidden behind a helper function, no?

**Comment by Egorand** [comment]
I've introduced a couple of helper properties:

1) You'll need helpers in both `TypeSpec` and `Builder`
2) Validations become complicated, e.g.:

```kotlin
val isAbstract = KModifier.ABSTRACT in modifiers || kind != Kind.CLASS || isEnum || isAnnotation
```

I'll give it more shots though, maybe I just need better helpers

**Comment by JakeWharton** [comment]
Yeah I'm not surprised at the internal complexity growing, but I think it
should be worth it to have the external model match that of the language
itself. Especially since we're going to get more things to model like
inline classes in the future.

**Pull request merged**
