### PR TITLE
Escape property and variable names if keywords

### PR DESCRIPTION
**Pull request by emrul**
PR for #476

### CODE REVIEW

**Comment by cypressious** [comment]
Kinda blocked by this

**Comment by emrul** [comment]
@Egorand done

**Comment by Egorand** [comment]
Thanks!

**Comment by cypressious** [comment]
@Egorand Would it be possible to merge this so that I can depend on the snapshot?

**Comment by cypressious** [comment]
Oh, I just noticed a bug:

I generate a type like so:

```kotlin
val typeBuilder = TypeSpec.classBuilder(name)
    .addProperties(properties.map {
        PropertySpec
            .varBuilder(it.key, parameterType(it.key, it.value))
            .initializer(it.key)
            .build()
    })
    .primaryConstructor(FunSpec.constructorBuilder()
        .addParameters(
            properties.map {
                ParameterSpec
                    .builder(it.key, parameterType(it.key, it.value))
                    .apply { if (it.value.optional) defaultValue("null") }
                    .build()
            }
        )
        .build())
```

and get the following result

```kotlin
class AlarmInfo(
    `when`: Float? = null,
    var delayInMinutes: Float? = null,
    var periodInMinutes: Float? = null
) {
    var `when`: Float? = when
}
```

**Comment by cypressious** [comment]
Maybe not a bug after all. If I manually escape the `.initializer(it.key)` part, it works. Still, not optimal.

**Comment by emrul** [comment]
@cypressious I had a look at this - I agree it is not optimal.  However, 'initialiser' passes off to CodeBlock and it seems automatic escaping is not carried out there.

I'm fairly new to the KotlinPoet internals but I can't see an effective way to auto-escape keywords within codeblocks; I think I'd have to leave that to the more experienced contributors.

**Comment by Egorand** [comment]
@cypressious can you file that please? Should be fixed in a follow-up PR

**Comment by cypressious** [comment]
Filed #483

**Comment by Egorand** [comment]
@emrul Sorry for keeping this open for a while. Can you please rebase and fix conflicts (we removed `varBuilder()`)?

**Comment by emrul** [comment]
@Egorand @shaishavgandhi05 apologies for the silence - I'm on the road for the next few weeks with very limited capability.  Hoping someone else can pick this up since it should remain a very simple change to rebase.

**Comment by shaishavgandhi05** [comment]
No problem! I can pick this up.

**Comment by Egorand** [comment]
Thanks @emrul!

**Pull request closed without merging**
