### PR TITLE
Update to gradle-mvn-publish 0.8.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by Egorand**
This release adds support for Dokka

### CODE REVIEW

**Comment by vanniktech** [comment]
Let me know whether this work or whether there's some additional stuff that needs be added to have proper support!

**Comment by Egorand** [comment]
Thanks Nick! I checked yesterday's snapshot (https://oss.sonatype.org/content/repositories/snapshots/com/squareup/kotlinpoet/1.1.0-SNAPSHOT/) and it looks like the javadoc jar is still empty. Since it was working fine when I tested it locally, it might be a problem with the config on our end. Will keep you posted.

**Comment by Egorand** [comment]
@vanniktech I re-checked our latest snapshots and it looks good! I'm really not sure why the earlier ones were empty. Waiting for the 0.8.0 release now.

**Comment by vanniktech** [comment]
Let me try out the script with a project of mine and I'll cut a release next week!

**Pull request merged**
