### PR TITLE
Goodbye jcenter

### PR DESCRIPTION
**Pull request by Egorand**
press-f

### CODE REVIEW

**Comment by Egorand** [comment]
Looks like Dokka hasn't migrated yet..

**Comment by ZacSweers** [comment]
I've got tricks for dokka

**Comment by Egorand** [comment]
@ZacSweers feel free to push into this PR!

**Comment by JakeWharton** [comment]
Is the trick waiting? Is there urgency? I would favor fewer tricks to maintain rather than simply waiting a bit.

**Comment by ZacSweers** [comment]
Bump up to Dokka 1.4.32 and you should be good to go

**Review by swankjesse — APPROVED** [review]

**Comment by Egorand** [comment]
https://github.com/square/kotlinpoet/pull/1068

**Pull request merged**
