### PR TITLE
Update dependency declaration in Download section

### PR DESCRIPTION
**Pull request by LouisCAD**
Replaces deprecated "compile"  configuration with "implementation", and make snippet Kotlin DSL compatible.

### CODE REVIEW

**Comment by Egorand** [comment]
Thanks @LouisCAD! Please sign our [CLA](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1) before I can merge this.

**Comment by LouisCAD** [comment]
I see you changed the CLA signing process as I already signed one to contribute to other Square projects, I submitted the form.

**Comment by JakeWharton** [comment]
The form is the canonical one. The other one is not.

**Comment by LouisCAD** [comment]
I meant I signed the form one too.

**Pull request merged**
