### PR TITLE
Setup Mkdocs website for documentation

### PR DESCRIPTION
**Pull request by ShaishavGandhi**
Inspired by [OkHttp](https://github.com/square/okhttp)!

This sets up a nice website for documentation as well as API docs. Here's what it essentially looks like in my fork: https://shaishavgandhi.github.io/kotlinpoet/

Feel free to suggest other colors 😅

### CODE REVIEW

**Comment by jemaystermind** [comment]
@ShaishavGandhi Is it possible to update the icon?

image

**Comment by Egorand** [comment]
THIS IS AWESOME!! Thanks a ton!

Can you please also add a custom CSS to use our fonts? https://github.com/square/okhttp/commit/a56f483cd2057ce019b6c9b55b1987c2076704f3

**Comment by ShaishavGandhi** [comment]
Added the custom CSS!



> @ShaishavGandhi Is it possible to update the icon?

I'm guessing OkHttp has the same problem? I didn't notice since I'm on dark mode on Mac. Happy to swap out it out for a black Square logo but I don't have the assets.

**Comment by Egorand** [comment]
Yeah, same, the icon looks good on dark tabs. Let's fix this in a followup.

**Comment by Egorand** [comment]
What are the deployment steps by the way?

**Comment by ShaishavGandhi** [comment]
Once it's merged, just run `./.buildscript deploy_website.sh` and it should deploy the website under https://square.github.io

**Comment by Egorand** [comment]
Sweet, merging!

**Pull request merged**
