### PR TITLE
Replace compile with implementation as compile is deprecated

### PR DESCRIPTION
**Pull request by ligi**

### CODE REVIEW

**Comment by ligi** [comment]
Oh dam - this form asks for a phone number - I do not have one (and neither would I put one in a google form If I would have one)

**Comment by Egorand** [comment]
@ligi I _think_ it shouldn't be mandatory, but let me ask around and get back to you.

**Comment by ligi** [comment]
Thanks - there is the required star on this field:
image

**Comment by Egorand** [comment]
Superseded by #951

**Pull request closed without merging**
