### PR TITLE
Correct statement formatting

### LINKED ISSUE #259: Improve formatting of property initializers
There are different formatting rules for property initializers, few examples below:

```kotlin
val a = "Hello !"
    .trim()
    .toLong()

val b = """
  a
  b
  c
  """

val c = { x: Int, y: Int ->
  x + y
}
```

Current implementation wraps the entire initializer in a statement, applying double indentation to every new line, hence the last example will be formatted as:

```kotlin
val c = { x: Int, y: Int ->
      x + y
    }
```

### PR DESCRIPTION
**Pull request by Egorand**
Closes #259

### CODE REVIEW

**Comment by Egorand** [comment]
Wanna add more documentation but would be great to have some feedback on the approach

**Comment by JakeWharton** [comment]
I'll try to look at this soon, but it's definitely going to miss the next release and I'm scrambling trying to finish slides so it might slip to early next week.

**Comment by swankjesse** [comment]
I’m a little lost on the motivation on this. The problem is that we’re indenting multiline strings too much?

**Comment by Egorand** [comment]
In general, our indentation logic for statements is dumb, as I believe Java's indenting logic is dumb as well. Kotlin apparently has more indentation rules.

**Comment by swankjesse** [comment]
I'd like to stall this until we update to the new style guide including 4-space indents everywhere.

That’s at least 3 parts:

 * Fix Square’s java-code-styles to match the Android spec.
 * Fix KotlinPoet’s own code to follow the guide
 * Fix emitted code to follow the guide.

The new rules are not my favorite, but I’d really like to just leave the world of manually wrapping and formatting in the past.

**Comment by JakeWharton** [comment]
For what it's worth, JetBrains own code base is 2 space so some level of
civil disobedience is allowed.

**Comment by Egorand** [comment]
Shall we switch to printing 4 spaces?

**Comment by swankjesse** [comment]
Yep. We want to move as quickly as possible to the way that Go programmers work, where humans don’t get to control the whitespace.

**Comment by swankjesse** [comment]
Close this?

**Comment by Egorand** [comment]
I'd agree that it's a minor bug, shall we close both the PR and the issue?

**Comment by swankjesse** [comment]
Done!

**Pull request closed without merging**
