### PR TITLE
add FileSpec.addWildcardImport method

### PR DESCRIPTION
**Pull request by evgeny-pasynkov**
Add ability to import the whole package into file

### CODE REVIEW

**Comment by JakeWharton** [comment]
We explicitly disallow wildcard imports.

**Comment by evgeny-pasynkov** [comment]
What is the reason for such restriction?
It is up to the user of the library how he would like to see generated code.
I agree that wildcard shouldn't be default - it has be stated directly.

My case: generated code could contain invocation of hundred extension methods - listing all of them is ridiculous

**Comment by evgeny-pasynkov** [comment]
With what I agree - adding wildcard import could be a little bit smarter: all individual imports should be removed when wildcard is present

**Comment by JakeWharton** [comment]
Wildcard imports are people writing code without an IDE. There's no reason to ever see them when using an IDE or when doing code generation since you explicitly know everything that's used.

You don't need to list them all. You only need to add one when you use it. KotlinPoet will de-dupe the list for you.

**Comment by Egorand** [comment]
Closing this. If there's an issue you're not able to overcome without wildcard imports we can look at it.

**Pull request closed without merging**
