### PR TITLE
Kotlin 1.6.0

### PR DESCRIPTION
**Pull request by Egorand**

### CODE REVIEW

**Review by ZacSweers — APPROVED** [review]

**Comment by Egorand** [comment]
@ZacSweers seeing test failures in this code, perhaps something's changed in the Metadata?

https://github.com/square/kotlinpoet/blob/43de7084390504c637f9d12c8beab51aa4c0e388/interop/kotlinx-metadata/src/main/kotlin/com/squareup/kotlinpoet/metadata/classinspectors/ReflectiveClassInspector.kt#L410-L422

**Comment by ZacSweers** [comment]
Looks like that method may not always be present, so just made it null-check now instead of an error

**Comment by ZacSweers** [comment]
We can also finally remove the experimental annotation from the reified `typeNameOf<>()` function and promote it to stable. Here's a patch you can use or I can PR it separately

```patch
Index: interop/javapoet/src/test/kotlin/com/squareup/kotlinpoet/javapoet/PoetInteropTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/interop/javapoet/src/test/kotlin/com/squareup/kotlinpoet/javapoet/PoetInteropTest.kt b/interop/javapoet/src/test/kotlin/com/squareup/kotlinpoet/javapoet/PoetInteropTest.kt
--- a/interop/javapoet/src/test/kotlin/com/squareup/kotlinpoet/javapoet/PoetInteropTest.kt	(revision 269c19af73379f084e7172938e7141c564739441)
+++ b/interop/javapoet/src/test/kotlin/com/squareup/kotlinpoet/javapoet/PoetInteropTest.kt	(date 1637217044220)
@@ -43,7 +43,7 @@
 import com.squareup.kotlinpoet.typeNameOf
 import org.junit.Test
 
-@OptIn(ExperimentalStdlibApi::class, KotlinPoetJavaPoetPreview::class)
+@OptIn(KotlinPoetJavaPoetPreview::class)
 class PoetInteropTest {
 
   @Test
Index: kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeNameKotlinTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeNameKotlinTest.kt b/kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeNameKotlinTest.kt
--- a/kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeNameKotlinTest.kt	(revision 269c19af73379f084e7172938e7141c564739441)
+++ b/kotlinpoet/src/test/java/com/squareup/kotlinpoet/TypeNameKotlinTest.kt	(date 1637217044226)
@@ -18,7 +18,6 @@
 import com.google.common.truth.Truth.assertThat
 import org.junit.Test
 
-@ExperimentalStdlibApi
 class TypeNameKotlinTest {
 
   @Test
Index: kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeName.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeName.kt b/kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeName.kt
--- a/kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeName.kt	(revision 269c19af73379f084e7172938e7141c564739441)
+++ b/kotlinpoet/src/main/java/com/squareup/kotlinpoet/TypeName.kt	(date 1637217044230)
@@ -294,5 +294,4 @@
  * Returns a [TypeName] equivalent of the reified type parameter [T] using reflection, maybe using kotlin-reflect
  * if required.
  */
-@ExperimentalStdlibApi
 public inline fun <reified T> typeNameOf(): TypeName = typeOf<T>().asTypeName()
Index: kotlinpoet/src/test/java/com/squareup/kotlinpoet/FileSpecTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/kotlinpoet/src/test/java/com/squareup/kotlinpoet/FileSpecTest.kt b/kotlinpoet/src/test/java/com/squareup/kotlinpoet/FileSpecTest.kt
--- a/kotlinpoet/src/test/java/com/squareup/kotlinpoet/FileSpecTest.kt	(revision 269c19af73379f084e7172938e7141c564739441)
+++ b/kotlinpoet/src/test/java/com/squareup/kotlinpoet/FileSpecTest.kt	(date 1637217044233)
@@ -1059,7 +1059,6 @@
   class WackyKey
   class OhNoThisDoesNotCompile
 
-  @OptIn(ExperimentalStdlibApi::class)
   @Test fun longCommentWithTypes() {
     val someLongParameterizedTypeName = typeNameOf<List<Map<in String, Collection<Map<WackyKey, out OhNoThisDoesNotCompile>>>>>()
     val param = ParameterSpec.builder("foo", someLongParameterizedTypeName).build()
Index: kotlinpoet/src/test/java/com/squareup/kotlinpoet/UtilTest.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/kotlinpoet/src/test/java/com/squareup/kotlinpoet/UtilTest.kt b/kotlinpoet/src/test/java/com/squareup/kotlinpoet/UtilTest.kt
--- a/kotlinpoet/src/test/java/com/squareup/kotlinpoet/UtilTest.kt	(revision 269c19af73379f084e7172938e7141c564739441)
+++ b/kotlinpoet/src/test/java/com/squareup/kotlinpoet/UtilTest.kt	(date 1637217044236)
@@ -96,7 +96,6 @@
     assertThat("with_unicode_punctuation\u2026".escapeIfNecessary()).isEqualTo("`with_unicode_punctuation\u2026`")
   }
 
-  @OptIn(ExperimentalStdlibApi::class)
   @Test fun escapeSpaceInName() {
     val generated = FileSpec.builder("a", "b")
       .addFunction(

```

**Comment by Egorand** [comment]
Do we need a release for Moshi?

**Comment by ZacSweers** [comment]
Nope!

**Comment by ZacSweers** [comment]
Though it may be nice to release for that removed experimental annotation

**Pull request merged**
