### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by Goooler** [comment]
CI should pass

image

**Review by Egorand — APPROVED** [review]
Thanks! Have you signed our [CLA](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1)?

**Comment by Goooler** [comment]
> Thanks! Have you signed our [CLA](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1)?

Not yet, how can I do ?

**Comment by Goooler** [comment]
> Thanks! Have you signed our [CLA](https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1)?

Done.

**Pull request merged**
