### PR TITLE
Bump mavenPublish to 0.18.0

### PR DESCRIPTION
**Pull request by Goooler**

### CODE REVIEW

**Comment by Egorand** [comment]
Anything noteworthy in the release notes? Linking to release notes in version bump PRs is super helpful!

**Comment by Goooler** [comment]
[Version 0.18.0 (2021-09-13)](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/CHANGELOG.md#version-0180-2021-09-13), seems nothing special to this repo.

**Comment by JakeWharton** [comment]
It removes the awful env var check which means we can finally upgrade from 0.14.2 on a bunch of projects.

**Comment by Egorand** [comment]
Dope, thanks!

**Review by Egorand — APPROVED** [review]

**Pull request merged**
