### PR TITLE
Adding ability to change initializers and defaultValues after being set

### LINKED ISSUE #1074: Enable method for overriding currently one-set values (initializer, getter, setter, etc)
I'm working on a project to generate Kotlin data classes from JsonSchema definitions. I'm providing fairly lightweight generation of the classes (not even bundling in anything Moshi/Gson/Jackson implementations in the core library) but want to enable an extensible implementation. I was thinking of exposing TypeSpec/ParameterSpec/PropertySpec to Interceptor interfaces of mine so that users of the library could change out property names/class names, add annotations, etc for each. 

I ran into a bit of a speed bump in that once some of the parts of some of these specs are called, they can't be overidden, even with a `.toBuilder()` call after being built. For example, I can't replace the `initializer` on a property, as I'll hit [an exception](https://github.com/square/kotlinpoet/blob/master/kotlinpoet/src/main/java/com/squareup/kotlinpoet/PropertySpec.kt#L235) about the initializer having already been set.

I realize I could certainly not expose KotlinPoet as the interface for the Interceptors, but I am lazy, and I would much rather not have to rewrite a bunch of functionality that's meant to line up to the codegen anyway.

I'm curious if you'd be open to changes that _at least_ enable this behavior, such as adding `allowOverride = false` to these functions such that they only validate the already-set case when `allowOverride` is `false`?

Interestingly, some parts of the API, such as `TypeSpec.primaryConstructor(...)` don't prevent setting multiple times. I could remove the set-once restriction in places they already exist, but I'm afraid that might break current implementations that may depend on that set-once exception throwing.

### PR DESCRIPTION
**Pull request by dallasgutauckis**
Adds support for 
 - clearing the initializer in PropertySpec
 - clearing the defaultValue in ParameterSpec

Closes #1074

### CODE REVIEW

**Review by Egorand — APPROVED** [review]
I'm okay with this solution but would also not be opposed to just removing the checks for double initialization. Not too worried about changing the behavior since it's undocumented. The checks were probably added to prevent accidentally setting those values multiple times, which IMO is not a very strong reason, and pretty sure we don't apply this approach consistently across the API.

**Comment by dallasgutauckis** [comment]
@Egorand appreciate the feedback. I'm fine going that route, but if we remove the checks we'd probably also want to make the parameter on at least the CodeBlock forms nullable:

i.e.

```kotlin
public fun defaultValue(codeBlock: CodeBlock): Builder = apply {
      check(this.defaultValue == null) { "initializer was already set" }
      this.defaultValue = codeBlock
    }
```

to become

```
public fun defaultValue(codeBlock: CodeBlock?): Builder = apply {
      this.defaultValue = codeBlock
    }
```

so that it's possible to clear the value from the Spec.

If you're okay with that, I'll make these changes :-)

**Comment by dallasgutauckis** [comment]
@Egorand assuming you're okay with this, I've made the suggested changes to:
 - Make the parameters nullable to support clearing
 - Make the various methods (defaultValue, initializer, etc) callable more than once and updating with the latest value

**Review by JakeWharton — APPROVED** [review]

**Review by Egorand — APPROVED** [review]
Yep, looks great, thanks @dallasgutauckis!

**Pull request merged**
